# Generated by Django 3.2.8 on 2021-11-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_date',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='photopost',
            name='image',
            field=models.ImageField(upload_to='photo/'),
        ),
    ]
