# Generated by Django 3.2.8 on 2021-11-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_auto_20211106_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatars/default.jpg', upload_to='avatars'),
        ),
    ]
